version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: ussd-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mtn_ussd
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./COMPLETE_DATABASE_SETUP.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ussd-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Spring Boot Backend
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: ussd-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mtn_ussd
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - ussd-network

  # Next.js Frontend
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: ussd-frontend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8080
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - ussd-network

networks:
  ussd-network:
    driver: bridge

volumes:
  mysql_data: